name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: List directory contents
      run: ls -la
    
    - name: Install Dependencies
      run: |
        cd client
        npm ci
    
    - name: Lint Check
      run: |
        cd client
        npm run lint
    
    - name: Run Tests
      run: |
        cd client
        npm test
    
    - name: Build
      run: |
        cd client
        npm run build
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: client/dist

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build
        path: client/dist
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/dist